spring.datasource.url=jdbc:postgresql://localhost:5432/meal
spring.datasource.username=postgres
spring.datasource.password=Vinnie559#
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
